# ref https://github.com/MichaelCurrin/jekyll-actions-quickstart/blob/master/.github/workflows/jekyll.yml
name: GH Pages CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
      - name: Run bundle install
        run: |
          bundle install
      - name: Build and deploy
        uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}